---

- name: Ставим необходимое ПО
  apt:
     name: [ 'apt-transport-https', 'uuid-runtime', 'pwgen', 'openjdk-8-jre-headless' ]
     state: latest
  become: yes

- name: Ставим ключ для репозитория ElasticSearch
  apt_key:
      url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
      state: present
  become: yes

- name: Подключаем репозиторий
  copy:
      src: "elastic.list"
      dest: "/etc/apt/sources.list.d/elastic-6.x.list"
  become: yes

- name: Обновим репозиторий и поставим ElasticSearch
  apt:
     update_cache: yes
     state: latest
     name: ['elasticsearch']
  become: yes
  notify: es_restart

- name: Копируем конфигурационный файл
  copy:
       src: "elasticsearch.yml"
       dest: "/etc/elasticsearch/elasticsearch.yml"
       backup: yes
  become: yes
  notify: es_restart

- name: Добавляем в автозапуск 
  service:
       name: "elasticsearch"
       enabled: yes
  become: yes
