---

- name: Подключаем репозиторий для Centos
  yum:
     name: "https://repo.zabbix.com/zabbix/4.4/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-4.4-1.el7.noarch.rpm"
     state: installed
  ignore_errors: yes
  become: yes
