---

 - name: Если репозиторий не подключен, то подключаем
   template: src=zabbix.list.j2 dest=/etc/apt/sources.list.d/zabbix.list mode=0644 owner=root group=root force=yes
   become: yes
   when: ansible_distribution == "Debian"

 - name: Если репозиторий не подключен, то подключаем
   template: src=zabbix.list.j2 dest=/etc/apt/sources.list.d/zabbix.list mode=0644 owner=root group=root force=yes
   become: yes
   when: ansible_distribution == "Ubuntu"

 - name: Добавляем ключ репозитория
   apt_key:
      keyserver: keyserver.ubuntu.com
      id: 082AB56BA14FE591
   become: yes
