---

# Инициализация

 - name: Подключаем переменные согласно дистрибутиву
   include_vars: "{{ item }}"
   with_first_found:
   - files:
     - "{{ ansible_distribution.ansible_distribution_version }}.yaml"
     skip: true

# Возня с репозиториями

# - name: Если Centos 6 то добавляем репозиторий CentOS
#   yum: 
#     name: "https://repo.zabbix.com/zabbix/3.4/rhel/6/x86_64/zabbix-release-3.4-1.el6.noarch.rpm"
#     state: installed
#   become: yes
#   when: ansible_distribution == "CentOS"
#   ignore_errors: true

 - include: tasks/debianrepo.yml
   when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

 - include: tasks/centosrepo.yml
   when: ansible_distribution == "CentOS"

 - include: tasks/agent.yml
   when: zabbix_agent

 - include: tasks/server.yml
   when: zabbix_server

 - include: tasks/web.yml
   when: zabbix_frontend
